import "./globals.css";
import { createGlobalStyle } from "styled-components";
import { ToggleThemeProvider } from "./utils/toggleTheme";
import BodyWrapper from "@/components/body";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ToggleThemeProvider>
        <BodyWrapper>
          {children}
        </BodyWrapper>
      </ToggleThemeProvider>
    </html>
  );
}
